### ISSUE TITLE
Doesn't work in a docker container volume

### ISSUE THREAD

**Issue by yspreen** [PickBas/unique_secret_key_generator#1]
If you want to persist the secret file in a docker container, the tool breaks, trying to delete the volume file:

```
   File "/usr/local/lib/python3.9/site-packages/secret_key_generator/generator_class.py", line 56, in _validate_secret_key
     os.remove(self._file_name)
 OSError: [Errno 16] Resource busy: '.secret.txt'
```

**Comment by PickBas** [comment]
Thank you for your contribution!

**Comment by yspreen** [comment]
Oh hey, that's gotta be a new record of 'time til merging first PR.' Thank you for the fast response!

That being said, maybe it was almost too fast, because I was naive enough to open the PR before deploying the fix in production and, sure enough, there was another line that needed to be changed. I'll open #3 to fix that! :)
